server:  
  port: ${PORT:2222}
spring:
  application:
    name: jasper-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
    tomcat:
      initial-size: 20
      max-active: 30
